version: 8.0.{build}
skip_tags: true
image: Visual Studio 2022
environment:
  access_token:
    secure: Eq6BjtZ80BXKLwFMg76IjuQAvbLjbojIF/X/ARouGVhxPneJtgDfCXMPNgJ7KBKq
  sonar_token:
    secure: W7pHKhuTW6Lh8WlXJNTOIaOzeuxLi+H6Nqmnm4pr28jM6jyIpOZ+1r10lIQi0eCA
  JAVA_HOME: C:\Program Files\Java\jdk19
nuget:
  disable_publish_on_pr: true
build_script:
  - dotnet restore
  - dotnet pack --include-symbols --include-source -c Release src\HtmlSanitizer
test_script:
  - ps: |
      if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"mganss_HtmlSanitizer" /v:$env:APPVEYOR_BUILD_VERSION /o:"mganss-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$env:sonar_token" /d:sonar.cs.opencover.reportsPaths="$($env:APPVEYOR_BUILD_FOLDER)\coverage.xml" /d:sonar.coverage.exclusions="**/Program.cs"
          dotnet build
      }
  - dotnet test /p:CollectCoverage=true test\HtmlSanitizer.Tests\HtmlSanitizer.Tests.csproj -f net6.0
  - ps: cp coverage.*.xml ./coverage.xml
  - ps: |
      if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
          dotnet sonarscanner end /d:sonar.login="$env:sonar_token"
      }
  - pip install codecov
  - codecov -f "coverage.xml"
artifacts:
  - path: 'src\**\*.*nupkg'
deploy:
  - provider: GitHub
    tag: v$(APPVEYOR_BUILD_VERSION)
    release: $(APPVEYOR_BUILD_VERSION)
    description: '$(APPVEYOR_REPO_COMMIT_MESSAGE)'
    auth_token:
      secure: Eq6BjtZ80BXKLwFMg76IjuQAvbLjbojIF/X/ARouGVhxPneJtgDfCXMPNgJ7KBKq
    draft: true
    on:
      branch: master
