version: 3.3.{build}-beta
environment:
  CoverityProjectToken:
    secure: pUUrynbyxCRpsAgGdKBVYDZCilwBmaWQ1Jg+rg5znr0=
  CoverityNotificationEmail:
    secure: m/ox72HU97EeJExWEFWx+0M9uov0cydn6E8mSaQzsQE=
build_script:
  - ps: (Get-Content src\HtmlSanitizer\project.json).Replace("1.0.0-VERSION", $env:APPVEYOR_BUILD_VERSION) | Set-Content src\HtmlSanitizer\project.json
  - dotnet restore
  - dotnet pack -c Release src\HtmlSanitizer
test_script:
  - dotnet test test\HtmlSanitizer.Tests
  - nuget.exe install OpenCover -ExcludeVersion
  - OpenCover\tools\OpenCover.Console.exe -register:user -filter:"+[HtmlSanitizer]*" -target:"C:\Program Files\dotnet\dotnet.exe" "-targetargs:test test\HtmlSanitizer.Tests" -returntargetcode -hideskipped:All -output:coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml"
artifacts:
  - path: 'src\**\*.nupkg'
