version: 6.0.{build}
skip_tags: true
image: Visual Studio 2019
environment:
  access_token:
    secure: Eq6BjtZ80BXKLwFMg76IjuQAvbLjbojIF/X/ARouGVhxPneJtgDfCXMPNgJ7KBKq
  sonar_token:
    secure: W7pHKhuTW6Lh8WlXJNTOIaOzeuxLi+H6Nqmnm4pr28jM6jyIpOZ+1r10lIQi0eCA
  JAVA_HOME: C:\Program Files\Java\jdk14
nuget:
  disable_publish_on_pr: true
build_script:
  - dotnet restore
  - dotnet pack --include-symbols --include-source -c Release src\HtmlSanitizer
test_script:
  - ps: |
      if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"mganss_HtmlSanitizer" /v:$env:APPVEYOR_BUILD_VERSION /o:"mganss-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$env:sonar_token" /d:sonar.cs.opencover.reportsPaths="$($env:APPVEYOR_BUILD_FOLDER)\coverage.net5.0.xml" /d:sonar.coverage.exclusions="**/Program.cs"
          dotnet build
      }
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="..\..\coverage.xml" test\HtmlSanitizer.Tests\HtmlSanitizer.Tests.csproj -f net5.0
  - ps: |
      if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
          dotnet sonarscanner end /d:sonar.login="$env:sonar_token"
      }
  - pip install codecov
  - codecov -f "coverage.net5.0.xml"
artifacts:
  - path: 'src\**\*.*nupkg'
deploy:
  - provider: GitHub
    tag: v$(APPVEYOR_BUILD_VERSION)
    release: $(APPVEYOR_BUILD_VERSION)
    description: '$(APPVEYOR_REPO_COMMIT_MESSAGE)'
    auth_token:
      secure: Eq6BjtZ80BXKLwFMg76IjuQAvbLjbojIF/X/ARouGVhxPneJtgDfCXMPNgJ7KBKq
    draft: true
    on:
      branch: master
